checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    nodes:
        analysis:
            tests:
                override:
                    -
                        command: pylint-run
                        use_website_config: true
            environment:
                node:
                    version: 6.0.0
        tests: true
filter:
    included_paths:
        - 'web/*'
        - 'executor/*'
