filter:
    paths:
        - 'web/*'
        - 'executor/*'
    excluded_paths:
        - '*/migrations/*'
        - '*/static/*'
        - '*/submfiles/*'
checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    dependencies:
        before:
            - pip install -r web/requirements.txt
            - pip install -r executor/requirements.txt
    environment:
        python: 3.4.0
        mysql: false
        postgresql: false
        mongodb: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
    tests:
        override:
            -
                command: './web/manage.py test'
