checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    tests:
        override:
            -
                command: './web/manage.py test opensubmit.tests'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
filter:
    paths:
        - 'web/*'
        - 'executor/*'
