language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r web/requirements.txt
  - pip install -r executor/requirements.txt
  - pip install scrutinizer-ocular
# command to run tests
script: make coverage
after_success:
  - ocular --access-token "37a231540cedfc2363fd2795caabe5497cbcfdb49dcd6f628cb7495e858547ca" --data-file "./.coverage" --config-file "./.coveragerc"
