language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r web/requirements.txt
  - pip install -r executor/requirements.txt
# command to run tests
script: cd web; ./manage.py test

