version: '3'

services:
  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: opensubmit
      POSTGRES_USER: opensubmit
      POSTGRES_DB: opensubmit
    volumes:
      - postgres-volume:/var/lib/postgresql/data  
  web:
    image: troeger/opensubmit-web
    environment:
      OPENSUBMIT_SERVER_HOST: http://${external_adr}
      OPENSUBMIT_SERVER_HOST_ALIASES: ${external_ip},web
      OPENSUBMIT_SERVER_MEDIAROOT: /data/media/ 
      OPENSUBMIT_DATABASE_NAME: opensubmit 
      OPENSUBMIT_DATABASE_USER: opensubmit 
      OPENSUBMIT_DATABASE_PASSWORD: opensubmit 
      OPENSUBMIT_DATABASE_HOST: db 
      OPENSUBMIT_LOGIN_GOOGLE_OAUTH_KEY: ${login_google_oauth_key}
      OPENSUBMIT_LOGIN_GOOGLE_OAUTH_SECRET: ${login_google_oauth_secret}
    tty: true
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - data-volume:/data
  exec:
    image: troeger/opensubmit-exec
    environment:
      OPENSUBMIT_SERVER_HOST: http://web
    tty: true
    depends_on:
      - web

volumes:
  data-volume:
  postgres-volume:
