version: '3'

services:
  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: opensubmit
      POSTGRES_USER: opensubmit
      POSTGRES_DB: opensubmit
    volumes:
      - postgres-volume:/var/lib/postgresql/data  
  web:
    image: troeger/opensubmit-web
    environment:
      OPENSUBMIT_SERVER_HOST: http://localhost:8000
      OPENSUBMIT_SERVER_HOST_ALIASES: web
      OPENSUBMIT_SERVER_MEDIAROOT: /data/media/ 
      OPENSUBMIT_DATABASE_NAME: opensubmit 
      OPENSUBMIT_DATABASE_USER: opensubmit 
      OPENSUBMIT_DATABASE_PASSWORD: opensubmit 
      OPENSUBMIT_DATABASE_HOST: db 
      OPENSUBMIT_LOGIN_GOOGLE_OAUTH_KEY: 631787075842-1e14uvstrno29bl9b684194lcq435p93.apps.googleusercontent.com
      OPENSUBMIT_LOGIN_GOOGLE_OAUTH_SECRET: o4_b20ieVruAr_-U-N6fFwEm
    build: 
      context: ./web/
    tty: true
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - data-volume:/data
  exec1:
    image: troeger/opensubmit-exec
    environment:
      OPENSUBMIT_SERVER_HOST: http://web
    build: 
      context: ./executor/
    tty: true
    depends_on:
      - web
  exec2:
    image: troeger/opensubmit-exec
    environment:
      OPENSUBMIT_SERVER_HOST: http://web
    build: 
      context: ./executor/
    tty: true
    depends_on:
      - web

volumes:
  data-volume:
  postgres-volume:
