apiVersion: v1
kind: ConfigMap
metadata:
  name: opensubmit-config
  labels:
    app.kubernetes.io/name: opensubmit
data:
  OPENSUBMIT_SERVER_URL: "https://beuth.open-submit.org"
  OPENSUBMIT_LOGIN_DEMO: "False"
  OPENSUBMIT_LOGIN_OIDC_DESCRIPTION: "Beuth Login"
  OPENSUBMIT_LOGIN_OIDC_ENDPOINT: "https://gitlab.beuth-hochschule.de"
  OPENSUBMIT_LOGIN_OIDC_CLIENT_ID: "bf7523e5c7898ff9c0ba24ef87c2331b73a44a2b9f2f8fef70e2cb26a2c99b22"
  OPENSUBMIT_LOGIN_OIDC_CLIENT_SECRET: "d9454e38e22ef5c1a87aaec986713f4f351bc8e3b92e075bee33b1c8fcb98c4e"
